---
- name: "create remote dir {{spark.remote_dir}}"
  file: path={{spark.remote_dir}} state=directory

- name: "create install dir {{spark.install_dir}}"
  file: path={{spark.install_dir}} state=directory

#- name: "Create spark data directory."
#  file: path={{item}} state=directory
#  with_items:
#    - "{{spark.journalnode_dir}}"
#    - "{{spark.tmp_dir}}"
#    - "{{spark.pid_dir}}"
#    - "{{spark.log_dir}}"
#    - "{{yarn_log_dir}}"
#    - "{{yarn_pid_dir}}"
#    - "{{yarn_nodemanager_local_dirs}}"
#    - "{{yarn_nodemanager_log_dirs}}"
#    - "{{yarn_app_mapreduce_am_staging_dir}}"
#    - "{{mapreduce_jobhistory_intermediate_done_dir}}"
#    - "{{mapreduce_jobhistory_done_dir}}"

- name: copy {{spark.filename}} to remote host {{spark.remote_dir}}
  copy: src={{spark.filename}} dest={{spark.remote_dir}}

- name: "unzip install package {{spark.filename}} to {{spark.install_dir}}"
  unarchive: 
    src: "{{spark.remote_dir}}/{{spark.filename}}"
    dest: "{{spark.install_dir}}"
    copy: no
    extra_opts:
     - --strip-components=1


