---

- name: "create remote dir {{hadoop.remote_dir}}"
  file: path={{hadoop.remote_dir}} state=directory

- name: "create install dir {{hadoop.install_dir}}"
  file: path={{hadoop.install_dir}} state=directory

- name: "Create hadoop data directory."
  file: path={{item}} state=directory
  with_items:
    - "{{hadoop.journalnode_dir}}"
    - "{{hadoop.tmp_dir}}"
    - "{{hadoop.pid_dir}}"
    - "{{hadoop.log_dir}}"
    - "{{yarn_log_dir}}"
    - "{{yarn_pid_dir}}"
    - "{{yarn_nodemanager_local_dirs}}"
    - "{{yarn_nodemanager_log_dirs}}"
    - "{{hadoop_mapred_pid_dir}}"
    - "{{hadoop_mapred_log_dir}}"

- name: copy {{hadoop.filename}} to remote host {{hadoop.remote_dir}}
  copy: src={{hadoop.filename}} dest={{hadoop.remote_dir}}

- name: "unzip install package {{hadoop.filename}} to {{hadoop.install_dir}}"
  unarchive: 
    src: "{{hadoop.remote_dir}}/{{hadoop.filename}}"
    dest: "{{hadoop.install_dir}}"
    copy: no
    extra_opts:
     - --strip-components=1

- name: set hadoop env
  tags: env
  lineinfile: dest={{hadoop.env_file}} insertafter="{{item.position}}" line="{{item.value}}" state=present
  with_items:
    - {position: EOF, value: "#########HADOOP ENV########"}
    - {position: EOF, value: "export HADOOP_HOME={{hadoop.install_dir}}"}
    - {position: EOF, value: "export PATH=$HADOOP_HOME/bin:$PATH"}
    
- name: enable hadoop env
  tags: env
  shell: "source {{hadoop.env_file}}"

- name: Write hadoop-env.sh file
  template: src=hadoop-env.sh.j2 dest={{hadoop.install_dir}}/etc/hadoop/hadoop-env.sh

- name: Write yarn-env.sh file
  template: src=yarn-env.sh.j2 dest={{hadoop.install_dir}}/etc/hadoop/yarn-env.sh

- name: Write mapred-env.sh file
  template: src=mapred-env.sh.j2 dest={{hadoop.install_dir}}/etc/hadoop/mapred-env.sh

- name: Write hdfs-site.xml file
  template: src=hdfs-site.xml.j2 dest={{hadoop.install_dir}}/etc/hadoop/hdfs-site.xml

- name: Write core-site.xml file
  template: src=core-site.xml.j2 dest={{hadoop.install_dir}}/etc/hadoop/core-site.xml

- name: Write mapred-site.xml file
  template: src=mapred-site.xml.j2 dest={{hadoop.install_dir}}/etc/hadoop/mapred-site.xml

- name: Write yarn-site.xml file
  template: src=yarn-site.xml.j2 dest={{hadoop.install_dir}}/etc/hadoop/yarn-site.xml

- name: Write slaves file
  template: src=slaves.j2 dest={{hadoop.install_dir}}/etc/hadoop/slaves

- name: start journalnode
  shell: "{{hadoop.install_dir}}/sbin/hadoop-daemon.sh start journalnode"
  when: jnnode == "true"

- name: format active namenode hdfs
  shell: "{{hadoop.install_dir}}/bin/hdfs namenode -format -force"
  when: namenode_active == "true"

- name: start active namenode hdfs
  shell: "{{hadoop.install_dir}}/sbin/hadoop-daemon.sh start namenode"
  when: namenode_active == "true"

- name: format standby namenode hdfs
  shell: "{{hadoop.install_dir}}/bin/hdfs namenode -bootstrapStandby -force"
  when: namenode_standby == "true"

- name: stop active namenode hdfs
  shell: "{{hadoop.install_dir}}/sbin/hadoop-daemon.sh stop namenode"
  when: namenode_active == "true"

- name: format ZKFC
  shell: "{{hadoop.install_dir}}/bin/hdfs zkfc -formatZK -force"
  when: namenode_active == "true"

- name: stop journalnode
  shell: "{{hadoop.install_dir}}/sbin/hadoop-daemon.sh stop journalnode"
  when: jnnode == "true"

- name: start namenode
  shell: "{{hadoop.install_dir}}/sbin/start-dfs.sh"
  when: namenode_active == "true"

- name: start yarn on namenode_active
  shell: "{{hadoop.install_dir}}/sbin/start-yarn.sh"
  when: namenode_active == "true"

- name: start standby rm on namenode_standby
  shell: "{{hadoop.install_dir}}/sbin/yarn-daemon.sh start resourcemanager"
  when: namenode_standby == "true"

- name: start jobhistory server on namenode_standby
  shell: "{{hadoop.install_dir}}/sbin/mr-jobhistory-daemon.sh start historyserver"
  when: namenode_standby == "true"
