---
- name: "create remote dir {{etcd.remote_dir}}"
  file: path={{etcd.remote_dir}} state=directory

- name: "create install dir {{etcd.install_dir}}"
  file: path={{etcd.install_dir}} state=directory

- name: "create etcd data directory."
  file: path={{item}} state=directory
  with_items:
    - "{{etcd.work_dir}}"

- name: copy {{etcd.filename}} to remote host {{etcd.remote_dir}}
  copy: src={{etcd.filename}} dest={{etcd.remote_dir}}

- name: "unzip install package {{etcd.filename}} to {{etcd.install_dir}}"
  unarchive: 
    src: "{{etcd.remote_dir}}/{{etcd.filename}}"
    dest: "{{etcd.install_dir}}"
    copy: no
    extra_opts:
     - --strip-components=1

