---
- name: reload systemctl daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: restart kubelet
  service: name=kubelet state=restarted

- name: restart kube-proxy
  service: name=kube-proxy state=restarted
