---
k8s:
 bin_dir: /root/soft/kubernetes/server/bin
 install_dir: /opt/kubernetes
 env_file: /etc/profile
 etc_dir: /etc/kubernetes
 kubelet_work_dir: /data/kubernetes/kubelet
 kubelet_log_dir: /data/kubernetes/kubelet_log
 kube_proxy_work_dir: /data/kubernetes/kube_proxy
 kube_proxy_log_dir: /data/kubernetes/kube_proxy_log

cni:
 bin_dir: /root/soft/cni/bin
 install_dir: /opt/cni
 etc_dir: /etc/cni/net.d

# 指向apiserver负载地址
KUBE_APISERVER: http://172.18.201.9:6888
CLUSTER_DNS: 10.68.0.2
CLUSTER_DOMAIN: cluster.local.
PAUSE_IAMGE: registry:5000/pause-amd64:3.0
ETCD_NDOES: "http://172.18.201.10:2379,http://172.18.201.11:2379,http://172.18.201.12:2379"
TOKEN: 8afdf3c4eb7c74018452423c29433609
# etcd_key_file
CALICO_KEY_PEM:
# etcd_cert_file
CALICO_PEM:
# etcd_ca_cert_file
CA_PEM:
