---
- name: "create remote dir {{hbase.remote_dir}}"
  file: path={{hbase.remote_dir}} state=directory

- name: "create install dir {{hbase.install_dir}}"
  file: path={{hbase.install_dir}} state=directory

- name: "Create hbase data directory."
  file: path={{item}} state=directory
  with_items:
    - "{{hbase.tmp_dir}}"
    - "{{hbase.pid_dir}}"
    - "{{hbase.log_dir}}"

- name: copy {{hbase.filename}} to remote host {{hbase.remote_dir}}
  copy: src={{hbase.filename}} dest={{hbase.remote_dir}}

- name: "unzip install package {{hbase.filename}} to {{hbase.install_dir}}"
  unarchive: 
    src: "{{hbase.remote_dir}}/{{hbase.filename}}"
    dest: "{{hbase.install_dir}}"
    copy: no
    extra_opts:
     - --strip-components=1

- name: Write hbase-site.xml file
  template: src=hbase-site.xml.j2 dest={{hbase.install_dir}}/conf/hbase-site.xml

- name: Write hbase-env.sh file
  template: src=hbase-env.sh.j2 dest={{hbase.install_dir}}/conf/hbase-env.sh

- name: Write regionservers file
  template: src=regionservers.j2 dest={{hbase.install_dir}}/conf/regionservers

- name: Write backup-masters file
  template: src=backup-masters.j2 dest={{hbase.install_dir}}/conf/backup-masters

#- name: start active hbase
#  shell: "{{hbase.install_dir}}/bin/start-hbase.sh"
#  when: hbase_active == "true"

